service: api-agendamentos

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  getAgendas:
    handler: src/agenda/controller/controller.getAgendas
    events:
      - http:
          path: agendas
          method: get

  createAgendamento:
    handler: src/agendamento/controller/controller.createAgendamento
    events:
      - http:
          path: agendamento
          method: post

custom:
  serverless-offline:
    httpPort: 3000
